
## Install all the development sources
install_request:
    stage: install
    cache:
        key: request-${CI_COMMIT_REF_SLUG}
        policy: push
        paths:
            - request/node_modules
    script:
        # Build local peer dependencies
        - cd utils
        - NODE_ENV=development npm install
        - npm run build
        - cd ..
        # Install module
        - cd request
        - NODE_ENV=development npm install
        - rm -rf node_modules/@jet-pack/utils
        - mkdir -p node_modules/@jet-pack/utils
        - cp -rf ../utils node_modules/@jet-pack/

lint_request:
    stage: lint
    cache:
        key: request-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - request/node_modules
    script:
        - cd request
        - npm run lint

test_node-8_request:
    stage: test
    image: node:8
    cache:
        key: request-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - request/node_modules
    script:
        - cd request
        - npm test

test_node-6_request:
    stage: test
    image: node:6
    cache:
        key: request-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - request/node_modules
    script:
        - cd request
        - npm test

test_node-10_request:
    stage: test
    image: node:10
    cache:
        key: request-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - request/node_modules
    script:
        - cd request
        - npm test

build_request:
    stage: build
    cache:
        key: request-${CI_COMMIT_REF_SLUG}
        policy: pull-push
        paths:
            - request/node_modules
            - request/dist
    script:
        - cd request
        - npm run build

dry-pack_request:
    stage: pack-dry
    cache:
        key: request-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - request/node_modules
            - request/dist
    script:
        - cd request
        - npm pack --dry-run

publish_request:
    stage: deploy
    only:
        - tags
    cache:
        key: request-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - request/node_modules
            - request/dist
    artifacts:
        paths:
            - request/request-*.tgz
    script:
        - cd request
        - npx nodexec publish:conditionally
