stages:
    - install
    - lint
    - test
    - deploy

cache:
    paths:
        - react-filter/node_modules
        - react-router/node_modules
        - request/node_modules
        - service-container/node_modules
        - store/node_modules
        - transform/node_modules
        - utils/node_modules
        - validation/node_modules
variables:
    NODE_ENV: "production"
    CI: "true"
image: node:8.16

## Install all the development sources
install:react-filter:
    stage: install
    script:
        - cd react-filter
        - NODE_ENV=development npm install

install:react-router:
    stage: install
    script:
        - cd react-router
        - NODE_ENV=development npm install

install:request:
    stage: install
    script:
        - cd request
        - NODE_ENV=development npm install

install:service-container:
    stage: install
    script:
        - cd service-container
        - NODE_ENV=development npm install

install:store:
    stage: install
    script:
        - cd store
        - NODE_ENV=development npm install

install:transform:
    stage: install
    script:
        - cd transform
        - NODE_ENV=development npm install

install:utils:
    stage: install
    script:
        - cd utils
        - NODE_ENV=development npm install

install:validation:
    stage: install
    script:
        - cd validation
        - NODE_ENV=development npm install
