
## Install all the development sources
install_react-filter:
    stage: install
    cache:
        key: react-filter-${CI_COMMIT_REF_SLUG}
        policy: push
        paths:
            - react-filter/node_modules
    script:
        - cd react-filter
        - NODE_ENV=development npm install

lint_react-filter:
    stage: lint
    cache:
        key: react-filter-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - react-filter/node_modules
    script:
        - cd react-filter
        - npm run lint

test_node-8_react-filter:
    stage: test
    image: node:8
    cache:
        key: react-filter-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - react-filter/node_modules
    script:
        - cd react-filter
        - npm test

test_node-6_react-filter:
    stage: test
    image: node:6
    cache:
        key: react-filter-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - react-filter/node_modules
    script:
        - cd react-filter
        - npm test

test_node-10_react-filter:
    stage: test
    image: node:10
    cache:
        key: react-filter-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - react-filter/node_modules
    script:
        - cd react-filter
        - npm test

build_react-filter:
    stage: build
    cache:
        key: react-filter-${CI_COMMIT_REF_SLUG}
        paths:
            - react-filter/node_modules
            - react-filter/dist
    script:
        - cd react-filter
        - npm run prepare
        - npm run build

publish_react-filter:
    stage: deploy
    only:
        - tags
    cache:
        key: react-filter-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - react-filter/node_modules
            - react-filter/dist
    script:
        - cd react-filter
        - npx nodexec publish:conditionally
