
## Install all the development sources
install_store:
    stage: install
    cache:
        key: store-${CI_COMMIT_REF_SLUG}
        policy: push
        paths:
            - store/node_modules
    script:
        - cd store
        - NODE_ENV=development npm install

lint_store:
    stage: lint
    cache:
        key: store-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - store/node_modules
    script:
        - cd store
        - npm run lint

test_node-8_store:
    stage: test
    image: node:8
    cache:
        key: store-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - store/node_modules
    script:
        - cd store
        - npm test

test_node-6_store:
    stage: test
    image: node:6
    cache:
        key: store-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - store/node_modules
    script:
        - cd store
        - npm test

test_node-10_store:
    stage: test
    image: node:10
    cache:
        key: store-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - store/node_modules
    script:
        - cd store
        - npm test

build_store:
    stage: build
    cache:
        key: store-${CI_COMMIT_REF_SLUG}
        policy: pull-push
        paths:
            - store/node_modules
            - store/dist
    script:
        - cd store
        - npm run build

dry-pack_store:
    stage: pack-dry
    cache:
        key: store-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - store/node_modules
            - store/dist
    script:
        - cd store
        - npm pack --dry-run

publish_store:
    stage: deploy
    only:
        - tags
    cache:
        key: store-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - store/node_modules
            - store/dist
    artifacts:
        paths:
            - store/store-*.tgz
    script:
        - cd store
        - npx nodexec publish:conditionally
