
## Install all the development sources
install_service-container:
    stage: install
    cache:
        key: service-container-${CI_COMMIT_REF_SLUG}
        policy: push
        paths:
            - service-container/node_modules
    script:
        - cd service-container
        - NODE_ENV=development npm install

lint_service-container:
    stage: lint
    cache:
        key: service-container-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - service-container/node_modules
    script:
        - cd service-container
        - npm run lint

test_node-8_service-container:
    stage: test
    image: node:8
    cache:
        key: service-container-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - service-container/node_modules
    script:
        - cd service-container
        - npm test

test_node-6_service-container:
    stage: test
    image: node:6
    cache:
        key: service-container-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - service-container/node_modules
    script:
        - cd service-container
        - npm test

test_node-10_service-container:
    stage: test
    image: node:10
    cache:
        key: service-container-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - service-container/node_modules
    script:
        - cd service-container
        - npm test

build_service-container:
    stage: build
    cache:
        key: service-container-${CI_COMMIT_REF_SLUG}
        policy: pull-push
        paths:
            - service-container/node_modules
            - service-container/dist
    script:
        - cd service-container
        - npm run build

publish_service-container:
    stage: deploy
    only:
        - tags
    cache:
        key: service-container-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - service-container/node_modules
            - service-container/dist
    script:
        - cd service-container
        - npx nodexec publish:conditionally
