
## Install all the development sources
install_utils:
    stage: install
    cache:
        key: utils-${CI_COMMIT_REF_SLUG}
        policy: push
        paths:
            - utils/node_modules
    script:
        - cd utils
        - NODE_ENV=development npm install

lint_utils:
    stage: lint
    cache:
        key: utils-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - utils/node_modules
    script:
        - cd utils
        - npm run lint

test_node-8_utils:
    stage: test
    image: node:8
    cache:
        key: utils-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - utils/node_modules
    script:
        - cd utils
        - npm test

test_node-6_utils:
    stage: test
    image: node:6
    cache:
        key: utils-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - utils/node_modules
    script:
        - cd utils
        - npm test

test_node-10_utils:
    stage: test
    image: node:10
    cache:
        key: utils-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - utils/node_modules
    script:
        - cd utils
        - npm test

build_utils:
    stage: build
    cache:
        key: utils-${CI_COMMIT_REF_SLUG}
        policy: pull-push
        paths:
            - utils/node_modules
            - utils/dist
    script:
        - cd utils
        - npm run build

dry-pack_utils:
    stage: pack-dry
    cache:
        key: utils-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - utils/node_modules
            - utils/dist
    script:
        - cd utils
        - npm pack --dry-run

publish_utils:
    stage: deploy
    only:
        - tags
    cache:
        key: utils-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - utils/node_modules
            - utils/dist
    script:
        - cd utils
        - npx nodexec publish:conditionally
