
## Install all the development sources
install_transform:
    stage: install
    cache:
        key: transform-${CI_COMMIT_REF_SLUG}
        policy: push
        paths:
            - transform/node_modules
    script:
        - cd transform
        - NODE_ENV=development npm install

lint_transform:
    stage: lint
    cache:
        key: transform-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - transform/node_modules
    script:
        - cd transform
        - npm run lint

test_node-8_transform:
    stage: test
    image: node:8
    cache:
        key: transform-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - transform/node_modules
    script:
        - cd transform
        - npm test

test_node-6_transform:
    stage: test
    image: node:6
    cache:
        key: transform-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - transform/node_modules
    script:
        - cd transform
        - npm test

test_node-10_transform:
    stage: test
    image: node:10
    cache:
        key: transform-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - transform/node_modules
    script:
        - cd transform
        - npm test

build_transform:
    stage: build
    cache:
        key: transform-${CI_COMMIT_REF_SLUG}
        policy: pull-push
        paths:
            - transform/node_modules
            - transform/dist
    script:
        - cd transform
        - npm run build

dry-pack_transform:
    stage: pack-dry
    cache:
        key: transform-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - transform/node_modules
            - transform/dist
    script:
        - cd transform
        - npm pack --dry-run

publish_transform:
    stage: deploy
    only:
        - tags
    cache:
        key: transform-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - transform/node_modules
            - transform/dist
    script:
        - cd transform
        - npx nodexec publish:conditionally
