
## Install all the development sources
install_validation:
    stage: install
    script:
        - cd validation
        - NODE_ENV=development npm install

lint_validation:
    stage: lint
    script:
        - cd validation
        - npm run lint

test_node-8_validation:
    stage: test
    image: node:8
    script:
        - cd validation
        - npm test

test_node-6_validation:
    stage: test
    image: node:6
    script:
        - cd validation
        - npm test

test_node-10_validation:
    stage: test
    image: node:10
    script:
        - cd validation
        - npm test

build_validation:
    stage: build
    script:
        - cd validation
        - npm run prepare
        - npm run build

publish_validation:
    stage: deploy
    only:
        - tags
    script:
        - cd validation
        - npx nodexec publish:conditionally
