
## Install all the development sources
install_validation:
    stage: install
    cache:
        key: validation-${CI_COMMIT_REF_SLUG}
        policy: push
        paths:
            - validation/node_modules
    script:
        - cd validation
        - NODE_ENV=development npm install

lint_validation:
    stage: lint
    cache:
        key: validation-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - validation/node_modules
    script:
        - cd validation
        - npm run lint

test_node-8_validation:
    stage: test
    image: node:8
    cache:
        key: validation-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - validation/node_modules
    script:
        - cd validation
        - npm test

test_node-6_validation:
    stage: test
    image: node:6
    cache:
        key: validation-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - validation/node_modules
    script:
        - cd validation
        - npm test

test_node-10_validation:
    stage: test
    image: node:10
    cache:
        key: validation-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - validation/node_modules
    script:
        - cd validation
        - npm test

build_validation:
    stage: build
    cache:
        key: validation-${CI_COMMIT_REF_SLUG}
        policy: pull-push
        paths:
            - validation/node_modules
            - validation/dist
    script:
        - cd validation
        - npm run prepare
        - npm run build

dry-pack_validation:
    stage: pack-dry
    cache:
        key: validation-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - validation/node_modules
            - validation/dist
    script:
        - cd validation
        - npm pack --dry-run

publish_validation:
    stage: deploy
    only:
        - tags
    cache:
        key: validation-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - validation/node_modules
            - validation/dist
    artifacts:
        paths:
            - validation-*.tgz
    script:
        - cd validation
        - npx nodexec publish:conditionally
