
## Install all the development sources
install_react-router:
    stage: install
    cache:
        key: react-router-${CI_COMMIT_REF_SLUG}
        policy: push
        paths:
            - react-router/node_modules
    script:
        - cd react-router
        - NODE_ENV=development npm install

lint_react-router:
    stage: lint
    cache:
        key: react-router-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - react-router/node_modules
    script:
        - cd react-router
        - npm run lint

test_node-8_react-router:
    stage: test
    image: node:8
    cache:
        key: react-router-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - react-router/node_modules
    script:
        - cd react-router
        - npm test

test_node-6_react-router:
    stage: test
    image: node:6
    cache:
        key: react-router-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - react-router/node_modules
    script:
        - cd react-router
        - npm test

test_node-10_react-router:
    stage: test
    image: node:10
    cache:
        key: react-router-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - react-router/node_modules
    script:
        - cd react-router
        - npm test

build_react-router:
    stage: build
    cache:
        key: react-router-${CI_COMMIT_REF_SLUG}
        policy: pull-push
        paths:
            - react-router/node_modules
            - react-router/dist
    script:
        - cd react-router
        - npm run build

dry-pack_react-router:
    stage: pack-dry
    cache:
        key: react-router-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - react-router/node_modules
            - react-router/dist
    script:
        - cd react-router
        - npm pack --dry-run

publish_react-router:
    stage: deploy
    only:
        - tags
    cache:
        key: react-router-${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - react-router/node_modules
            - react-router/dist
    artifacts:
        paths:
            - react-router/react-router-*.tgz
    script:
        - cd react-router
        - npx nodexec publish:conditionally
